first_name = str(input("Enter your first name: "))
last_name = str(input("Enter your last name: "))
age = int(input("Enter your age: "))
hometown = str(input("Enter your hometown: "))
print(first_name)
print(last_name)
print(age)
print(hometown)
print("Hello, my name is " + first_name + " " + last_name + " and I am " + str(age) + " years old. I come from " + hometown + ".")